noinst_PROGRAMS =
noinst_PROGRAMS += test-bson
noinst_PROGRAMS += test-bson-iter
noinst_PROGRAMS += test-bson-json
noinst_PROGRAMS += test-bson-oid
noinst_PROGRAMS += test-bson-reader
noinst_PROGRAMS += test-bson-string
noinst_PROGRAMS += test-bson-utf8


TEST_PROGS =
TEST_PROGS += test-bson
TEST_PROGS += test-bson-iter
TEST_PROGS += test-bson-json
TEST_PROGS += test-bson-oid
TEST_PROGS += test-bson-reader
TEST_PROGS += test-bson-string
TEST_PROGS += test-bson-utf8


test_bson_SOURCES = $(top_srcdir)/tests/test-bson.c
test_bson_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_LDADD = libbson-1.0.la


test_bson_iter_SOURCES = $(top_srcdir)/tests/test-bson-iter.c
test_bson_iter_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_iter_LDADD = libbson-1.0.la


test_bson_json_SOURCES = $(top_srcdir)/tests/test-bson-json.c
test_bson_json_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_json_LDADD = libbson-1.0.la


test_bson_oid_SOURCES = $(top_srcdir)/tests/test-bson-oid.c
test_bson_oid_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_oid_LDADD = libbson-1.0.la -lpthread


test_bson_reader_SOURCES = $(top_srcdir)/tests/test-bson-reader.c
test_bson_reader_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_reader_LDADD = libbson-1.0.la


test_bson_string_SOURCES = $(top_srcdir)/tests/test-bson-string.c
test_bson_string_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_string_LDADD = libbson-1.0.la


test_bson_utf8_SOURCES = $(top_srcdir)/tests/test-bson-utf8.c
test_bson_utf8_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_utf8_LDADD = libbson-1.0.la


test: $(TESTS)
	@ for TEST_PROG in $(TEST_PROGS) ; do \
		./$$TEST_PROG ; \
	done
	@ LD_LIBRARY_PATH=.libs DYLD_LIBRARY_PATH=.libs PYTHONPATH=.libs ./tests/test_cbson.py
