noinst_PROGRAMS = \
	test-bson \
	test-bson-clock \
	test-bson-endian \
	test-bson-error \
	test-bson-iter \
	test-bson-json \
	test-bson-oid \
	test-bson-reader \
	test-bson-string \
	test-bson-utf8 \
	test-bson-writer


TEST_PROGS = \
	test-bson \
	test-bson-clock \
	test-bson-endian \
	test-bson-error \
	test-bson-iter \
	test-bson-json \
	test-bson-oid \
	test-bson-reader \
	test-bson-string \
	test-bson-utf8 \
	test-bson-writer


if OS_LINUX
TEST_PROGS += $(top_srcdir)/tests/abicheck.sh
endif


EXTRA_DIST += \
	tests/bson-tests.h \
	tests/binary/dollarquery.bson \
	tests/binary/dotkey.bson \
	tests/binary/dotquery.bson \
	tests/binary/eurokey.bson \
	tests/binary/overflow1.bson \
	tests/binary/overflow2.bson \
	tests/binary/overflow3.bson \
	tests/binary/overflow4.bson \
	tests/binary/readergrow.bson \
	tests/binary/stackoverflow.bson \
	tests/binary/stream.bson \
	tests/binary/stream_corrupt.bson \
	tests/binary/test10.bson \
	tests/binary/test11.bson \
	tests/binary/test12.bson \
	tests/binary/test13.bson \
	tests/binary/test14.bson \
	tests/binary/test15.bson \
	tests/binary/test16.bson \
	tests/binary/test17.bson \
	tests/binary/test18.bson \
	tests/binary/test19.bson \
	tests/binary/test1.bson \
	tests/binary/test20.bson \
	tests/binary/test21.bson \
	tests/binary/test22.bson \
	tests/binary/test23.bson \
	tests/binary/test24.bson \
	tests/binary/test25.bson \
	tests/binary/test26.bson \
	tests/binary/test27.bson \
	tests/binary/test28.bson \
	tests/binary/test29.bson \
	tests/binary/test2.bson \
	tests/binary/test30.bson \
	tests/binary/test31.bson \
	tests/binary/test32.bson \
	tests/binary/test33.bson \
	tests/binary/test34.bson \
	tests/binary/test35.bson \
	tests/binary/test36.bson \
	tests/binary/test37.bson \
	tests/binary/test38.bson \
	tests/binary/test39.bson \
	tests/binary/test3.bson \
	tests/binary/test4.bson \
	tests/binary/test40.bson \
	tests/binary/test41.bson \
	tests/binary/test42.bson \
	tests/binary/test43.bson \
	tests/binary/test44.bson \
	tests/binary/test45.bson \
	tests/binary/test46.bson \
	tests/binary/test47.bson \
	tests/binary/test48.bson \
	tests/binary/test49.bson \
	tests/binary/test5.bson \
	tests/binary/test50.bson \
	tests/binary/test51.bson \
	tests/binary/test52.bson \
	tests/binary/test53.bson \
	tests/binary/test54.bson \
	tests/binary/test55.bson \
	tests/binary/test56.bson \
	tests/binary/test6.bson \
	tests/binary/test7.bson \
	tests/binary/test8.bson \
	tests/binary/test9.bson \
	tests/binary/trailingnull.bson


test_bson_SOURCES = tests/test-bson.c
test_bson_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_LDADD = libbson-1.0.la


test_bson_clock_SOURCES = tests/test-bson-clock.c
test_bson_clock_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_clock_LDADD = libbson-1.0.la


test_bson_endian_SOURCES = tests/test-endian.c
test_bson_endian_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_endian_LDADD = libbson-1.0.la


test_bson_error_SOURCES = tests/test-bson-error.c
test_bson_error_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_error_LDADD = libbson-1.0.la


test_bson_iter_SOURCES = tests/test-bson-iter.c
test_bson_iter_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_iter_LDADD = libbson-1.0.la


test_bson_json_SOURCES = tests/test-bson-json.c
test_bson_json_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_json_LDADD = libbson-1.0.la


test_bson_oid_SOURCES = tests/test-bson-oid.c
test_bson_oid_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_oid_LDADD = libbson-1.0.la


test_bson_reader_SOURCES = tests/test-bson-reader.c
test_bson_reader_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_reader_LDADD = libbson-1.0.la


test_bson_string_SOURCES = tests/test-bson-string.c
test_bson_string_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_string_LDADD = libbson-1.0.la


test_bson_utf8_SOURCES = tests/test-bson-utf8.c
test_bson_utf8_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_utf8_LDADD = libbson-1.0.la


test_bson_writer_SOURCES = tests/test-bson-writer.c
test_bson_writer_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_writer_LDADD = libbson-1.0.la


if HAVE_PYTHON
PYTEST_DEPS = cbson.la
endif


test: $(TEST_PROGS) $(PYTEST_DEPS)
	@ for TEST_PROG in $(TEST_PROGS) ; do \
		libtool --mode=execute $$VALGRIND ./$$TEST_PROG ; \
	done
if HAVE_PYTHON
	@ LD_LIBRARY_PATH=.libs DYLD_LIBRARY_PATH=.libs PYTHONPATH=.libs ./tests/test_cbson.py
endif
