noinst_PROGRAMS =
noinst_PROGRAMS += test-bson
noinst_PROGRAMS += test-bson-clock
noinst_PROGRAMS += test-bson-error
noinst_PROGRAMS += test-bson-iter
noinst_PROGRAMS += test-bson-json
noinst_PROGRAMS += test-bson-oid
noinst_PROGRAMS += test-bson-reader
noinst_PROGRAMS += test-bson-string
noinst_PROGRAMS += test-bson-utf8
noinst_PROGRAMS += test-bson-writer


TEST_PROGS =
TEST_PROGS += test-bson
TEST_PROGS += test-bson-clock
TEST_PROGS += test-bson-error
TEST_PROGS += test-bson-iter
TEST_PROGS += test-bson-json
TEST_PROGS += test-bson-oid
TEST_PROGS += test-bson-reader
TEST_PROGS += test-bson-string
TEST_PROGS += test-bson-utf8
TEST_PROGS += test-bson-writer


EXTRA_DIST += $(top_srcdir)/tests/bson-tests.h
EXTRA_DIST += $(top_srcdir)/tests/binary/dollarquery.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/dotkey.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/dotquery.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/eurokey.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/overflow1.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/overflow2.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/overflow3.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/overflow4.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/readergrow.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/stackoverflow.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/stream.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/stream_corrupt.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test10.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test11.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test12.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test13.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test14.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test15.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test16.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test17.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test18.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test19.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test1.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test20.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test21.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test22.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test23.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test24.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test25.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test26.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test27.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test28.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test29.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test2.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test30.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test31.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test32.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test33.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test34.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test35.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test36.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test37.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test38.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test39.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test3.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test4.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test5.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test6.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test7.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test8.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/test9.bson
EXTRA_DIST += $(top_srcdir)/tests/binary/trailingnull.bson


test_bson_SOURCES = $(top_srcdir)/tests/test-bson.c
test_bson_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_LDADD = libbson-1.0.la


test_bson_clock_SOURCES = $(top_srcdir)/tests/test-bson-clock.c
test_bson_clock_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_clock_LDADD = libbson-1.0.la


test_bson_error_SOURCES = $(top_srcdir)/tests/test-bson-error.c
test_bson_error_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_error_LDADD = libbson-1.0.la


test_bson_iter_SOURCES = $(top_srcdir)/tests/test-bson-iter.c
test_bson_iter_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_iter_LDADD = libbson-1.0.la


test_bson_json_SOURCES = $(top_srcdir)/tests/test-bson-json.c
test_bson_json_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_json_LDADD = libbson-1.0.la


test_bson_oid_SOURCES = $(top_srcdir)/tests/test-bson-oid.c
test_bson_oid_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_oid_LDADD = libbson-1.0.la


test_bson_reader_SOURCES = $(top_srcdir)/tests/test-bson-reader.c
test_bson_reader_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_reader_LDADD = libbson-1.0.la


test_bson_string_SOURCES = $(top_srcdir)/tests/test-bson-string.c
test_bson_string_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_string_LDADD = libbson-1.0.la


test_bson_utf8_SOURCES = $(top_srcdir)/tests/test-bson-utf8.c
test_bson_utf8_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_utf8_LDADD = libbson-1.0.la


test_bson_writer_SOURCES = $(top_srcdir)/tests/test-bson-writer.c
test_bson_writer_CPPFLAGS = -I$(top_srcdir) -DBSON_COMPILATION
test_bson_writer_LDADD = libbson-1.0.la


if HAVE_PYTHON
PYTEST_DEPS = cbson.la
endif


test: $(TEST_PROGS) $(PYTEST_DEPS)
	@ for TEST_PROG in $(TEST_PROGS) ; do \
		./$$TEST_PROG ; \
	done
if HAVE_PYTHON
	@ LD_LIBRARY_PATH=.libs DYLD_LIBRARY_PATH=.libs PYTHONPATH=.libs ./tests/test_cbson.py
endif
